// Deno test: renderCertificatePdf golden invariants.
//
// This is the A2 safety net for the certificate renderer. It doesn't do full
// text extraction (no Deno-friendly PDF text extractor is in the runtime yet)
// but it locks down every regression class the audit cared about:
//
//   1. The renderer produces a real, well-formed PDF (starts with %PDF-,
//      round-trips through pdf-lib, has ≥1 page).
//   2. The output size sits inside a sane band. A P9 with the full section
//      set + a posted fiscal year has to be at least a few KB — an empty
//      renderer (blank sections, silently swallowed errors) would fall
//      below the floor. It also can't runaway past a ceiling — that would
//      mean glyph substitution or infinite pagination.
//   3. The renderer accepts the exact section set the KE P9 v2 template
//      declares (employer_header, employee_header, fiscal_period_band,
//      monthly_breakdown with the PAYE column set, ytd_table, relief_summary,
//      signature_block, statutory_footnote). Renderer changes that drop
//      support for one of these section types fail this test.
//
// If we later add a Deno pdf-text extractor (unpdf, pdfjs-serverless, etc.)
// extend this test with token-level assertions ("P9 — Tax Deduction Card",
// month labels, PAYE column headers) to catch kerning / glyph substitution
// bugs directly.
import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { PDFDocument } from "https://esm.sh/pdf-lib@1.17.1";
import { renderCertificatePdf } from "./certificateRenderer.ts";
import type { CertificateTemplate, CertificatePayload } from "./certificateRenderer.ts";

const FIXTURE_TEMPLATE: CertificateTemplate = {
  code: "P9",
  display_name: "P9 — Tax Deduction Card",
  legal_reference: "Income Tax Act, CAP 470",
  regulation_citation: "Sec. 37",
  effective_date: "2024-07-01",
  authority_name: "Kenya Revenue Authority",
  body: {
    data_source: "payroll_employee_ytd",
    sections: [
      { type: "employer_header", include: ["name", "tax_pin", "address", "tax_office"] },
      { type: "employee_header", include: ["employee_number", "tax_pin", "national_id", "position"] },
      { type: "fiscal_period_band" },
      {
        type: "monthly_breakdown",
        title: "PAYE monthly breakdown",
        columns: [
          { key: "basic_pay", header: "Basic" },
          { key: "allowances", header: "Allow." },
          { key: "gross_pay", header: "Gross" },
          { key: "nssf", header: "NSSF" },
          { key: "shif", header: "SHIF" },
          { key: "housing_levy", header: "Housing" },
          { key: "paye", header: "PAYE" },
          { key: "net_pay", header: "Net" },
        ],
      },
      { type: "ytd_table" },
      { type: "relief_summary" },
      { type: "signature_block", include: ["preparer", "date", "employer_stamp"] },
      {
        type: "statutory_footnote",
        body:
          "Issued under Section 37 of the Income Tax Act, CAP 470. This " +
          "certificate must accompany the employee's annual self-assessment " +
          "return where applicable.",
      },
    ],
    footer_note: "Generated by AccrualFlow.",
  },
};

const MONTHS = 12;
const PAYE_CODES = [
  "basic_pay", "allowances", "gross_pay", "nssf", "shif",
  "housing_levy", "paye", "net_pay",
];

function buildFixturePayload(): CertificatePayload {
  const monthly = [] as CertificatePayload["monthly"];
  for (let m = 1; m <= MONTHS; m++) {
    for (const code of PAYE_CODES) {
      monthly.push({
        month_index: m,
        rule_code: code,
        category: "statutory",
        employee_amount: code === "net_pay" ? 42000 : 5000,
        employer_amount: 0,
        taxable_amount: code === "gross_pay" ? 60000 : 0,
      } as any);
    }
  }
  const ytdRows = PAYE_CODES.map((code) => ({
    rule_code: code,
    category: "statutory",
    employee_amount: (code === "net_pay" ? 42000 : 5000) * MONTHS,
    employer_amount: 0,
    taxable_amount: code === "gross_pay" ? 60000 * MONTHS : 0,
  }));
  return {
    employee: {
      full_name: "Jane Wanjiku",
      employee_number: "EMP-001",
      tax_pin: "A123456789Z",
      national_id: "12345678",
      position: "Senior Accountant",
      department: "Finance",
      hire_date: "2022-01-15",
    },
    employer: {
      name: "Acme Kenya Ltd",
      tax_pin: "P051234567X",
      address: "P.O. Box 1234-00100, Nairobi",
      tax_office: "Nairobi North",
      phone: "+254 700 000 000",
      email: "hr@acme.co.ke",
    },
    fiscal_year: 2025,
    period_label: "01 Jan 2025 – 31 Dec 2025",
    currency: "KES",
    monthly,
    ytdRows,
    totals: {
      employee: PAYE_CODES.reduce((a, c) => a + (c === "net_pay" ? 42000 : 5000) * MONTHS, 0),
      employer: 0,
      taxable: 60000 * MONTHS,
    },
    serial_number: "TC-2025-000001",
    generated_at: "2026-01-15T09:00:00Z",
  };
}

Deno.test("renderCertificatePdf produces a well-formed P9 PDF", async () => {
  const bytes = await renderCertificatePdf(FIXTURE_TEMPLATE, buildFixturePayload());

  // (1) Well-formed PDF header.
  assert(bytes.length > 0, "renderer returned empty bytes");
  const header = new TextDecoder().decode(bytes.slice(0, 5));
  assertEquals(header, "%PDF-", `expected %PDF- header, got: ${header}`);

  // (2) Size floor / ceiling — a P9 with 12×8 monthly rows + YTD + all
  //     identity + signature bands can't be under 4 KB, and can't credibly
  //     exceed 400 KB (would indicate embedded raster or glyph blowup).
  assert(bytes.length >= 4 * 1024, `P9 output too small (${bytes.length}B) — sections likely rendered empty`);
  assert(bytes.length <= 400 * 1024, `P9 output too large (${bytes.length}B) — check for glyph substitution / raster leak`);

  // (3) Round-trips through pdf-lib and reports a plausible page count.
  const parsed = await PDFDocument.load(bytes);
  const pageCount = parsed.getPageCount();
  assert(pageCount >= 1 && pageCount <= 4, `unexpected page count: ${pageCount}`);
});

Deno.test("renderCertificatePdf tolerates sparse monthly data without crashing", async () => {
  // Simulates a fiscal year with only one posted payslip — the dense-grid
  // RPC (A1) still returns 12 rows, most zero-filled. Renderer must draw
  // them without regressing to a single-row band.
  const payload = buildFixturePayload();
  payload.monthly = payload.monthly.map((r) => ({
    ...r,
    employee_amount: r.month_index === 1 ? r.employee_amount : 0,
    employer_amount: 0,
    taxable_amount: r.month_index === 1 ? r.taxable_amount : 0,
  }));
  const bytes = await renderCertificatePdf(FIXTURE_TEMPLATE, payload);
  assert(bytes.length >= 4 * 1024, "sparse-month P9 should still render a full 12-row band");
  const parsed = await PDFDocument.load(bytes);
  assert(parsed.getPageCount() >= 1);
});