/**
 * PDF Report Cache
 * 
 * L2 FIX: Simple in-memory cache for generated PDFs with TTL.
 * Prevents redundant edge function calls for the same report config.
 */

interface CacheEntry {
  blob: Blob;
  expiresAt: number;
}

const PDF_CACHE = new Map<string, CacheEntry>();
const DEFAULT_TTL_MS = 5 * 60 * 1000; // 5 minutes

/**
 * Generates a cache key from report export config.
 */
function stableStringify(value: unknown): string {
  if (value === null || typeof value === "number" || typeof value === "string" || typeof value === "boolean") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(",")}]`;
  }
  if (typeof value === "object" && value !== undefined) {
    return `{${Object.keys(value as Record<string, unknown>)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableStringify((value as Record<string, unknown>)[key])}`)
      .join(",")}}`;
  }
  return "null";
}

/** FNV-1a — small, deterministic content identity for cache keys. */
function contentHash(value: unknown): string {
  const text = stableStringify(value);
  let hash = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return `${(hash >>> 0).toString(16)}:${text.length}`;
}

function getCacheKey(config: {
  title?: string;
  dateRange?: string;
  asOf?: string;
  subtitle?: string;
  organizationId?: string;
  businessId?: string;
  branchId?: string | null;
  reportType?: string;
  formatProfile?: "financial" | "operational";
  columns?: any[];
  rows?: any[];
}): string {
  return JSON.stringify({
    // Increment whenever the server-side PDF presentation contract changes.
    // This prevents a browser tab from serving an artifact generated by an
    // older deployed renderer after a masthead/profile update.
    v: 6,
    t: config.title,
    s: config.subtitle,
    d: config.dateRange,
    a: config.asOf,
    o: config.organizationId,
    b: config.businessId,
    br: config.branchId,
    rt: config.reportType,
    fp: config.formatProfile,
    // Full content identity, not first/last row samples. A middle-row amount
    // change must never collide with the PDF generated before it.
    c: contentHash(config.columns ?? []),
    r: contentHash(config.rows ?? []),
  });
}

/**
 * Retrieve a cached PDF blob if it exists and hasn't expired.
 */
export function getCachedPdf(config: Parameters<typeof getCacheKey>[0]): Blob | null {
  const key = getCacheKey(config);
  const entry = PDF_CACHE.get(key);
  if (!entry) return null;
  if (Date.now() > entry.expiresAt) {
    PDF_CACHE.delete(key);
    return null;
  }
  return entry.blob;
}

/**
 * Store a PDF blob in cache with optional TTL.
 */
export function cachePdf(
  config: Parameters<typeof getCacheKey>[0],
  blob: Blob,
  ttlMs: number = DEFAULT_TTL_MS
): void {
  const key = getCacheKey(config);
  PDF_CACHE.set(key, {
    blob,
    expiresAt: Date.now() + ttlMs,
  });

  // Evict old entries if cache gets too large
  if (PDF_CACHE.size > 20) {
    const now = Date.now();
    for (const [k, v] of PDF_CACHE) {
      if (now > v.expiresAt) PDF_CACHE.delete(k);
    }
  }
}

/**
 * Clear all cached PDFs.
 */
export function clearPdfCache(): void {
  PDF_CACHE.clear();
}
