/**
 * PackArtifactPanel — delegation surface for pack-owned reports.
 *
 * Statutory returns (P10, NSSF, SHIF, AHL, HELB, NITA, Ghana PAYE, …)
 * and tax certificates (P9, P9A, Certificate of Service, Ghana annual,
 * …) are generated by ONE canonical engine each:
 *
 *   pack_artifact.statutory_return → supabase/functions/generate-statutory-return
 *   pack_artifact.tax_certificate  → supabase/functions/generate-tax-certificate
 *
 * The Reporting Centre catalogs these documents (owner rail: Compliance /
 * pack country). The **workflow** for generating and filing them lives
 * in Statutory Remittances and the Tax Certificates page. This panel
 * therefore never re-implements generation — it delegates.
 *
 * Doing this cleanly is the point of the architecture: the same
 * document has ONE generator and TWO entry points (catalog + workflow).
 */
import { Link } from "react-router-dom";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";
import type { PayrollReportDefinition } from "@/hooks/payroll/usePayrollReportDefinitions";

interface Props {
  definition: PayrollReportDefinition;
  dateFrom: string;
  dateTo: string;
}

export function PackArtifactPanel({ definition, dateFrom, dateTo }: Props) {
  const isReturn = definition.dataSource === "pack_artifact.statutory_return";
  const isCertificate = definition.dataSource === "pack_artifact.tax_certificate";

  const workflowHref = isReturn
    ? `/hr/remittances?template=${encodeURIComponent(
        String((definition.metadata as any)?.template_code ?? ""),
      )}&from=${dateFrom}&to=${dateTo}`
    : isCertificate
      ? `/hr/payroll/tax-certificates?template=${encodeURIComponent(
          String((definition.metadata as any)?.template_code ?? ""),
        )}&from=${dateFrom}&to=${dateTo}`
      : "/hr/payroll";

  const workflowLabel = isReturn
    ? "Open Statutory Remittances"
    : isCertificate
      ? "Open Tax Certificates"
      : "Open workflow";

  const bodyCopy = isReturn
    ? "This statutory return is produced by the Statutory Remittances workflow. Generate, review, file and reconcile it there — Reports catalogues it here so it is discoverable but does not duplicate the generator."
    : isCertificate
      ? "This tax certificate is produced by the Tax Certificates workflow. Generate, issue and download individual certificates there — Reports catalogues the template here without duplicating the engine."
      : "This report is produced by another workflow. Open it there.";

  return (
    <Card>
      <CardContent className="space-y-4 py-8">
        <div className="max-w-2xl space-y-2">
          <h3 className="text-base font-semibold">{definition.label}</h3>
          <p className="text-sm text-muted-foreground">{bodyCopy}</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button asChild>
            <Link to={workflowHref}>
              <ExternalLink className="mr-2 h-4 w-4" />
              {workflowLabel}
            </Link>
          </Button>
          <Button variant="outline" asChild>
            <Link to="/hr/payroll/reports">Back to Reporting Centre</Link>
          </Button>
        </div>
        <div className="text-xs text-muted-foreground">
          Canonical engine:{" "}
          <code className="rounded bg-muted px-1 py-0.5 text-[11px]">
            {definition.artifactGenerator ?? "—"}
          </code>
        </div>
      </CardContent>
    </Card>
  );
}

export default PackArtifactPanel;
