/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalizationPreviewKindTemplateCodeRouteImport } from './routes/localization.preview.$kind.$templateCode'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizationPreviewKindTemplateCodeRoute =
  LocalizationPreviewKindTemplateCodeRouteImport.update({
    id: '/localization/preview/$kind/$templateCode',
    path: '/localization/preview/$kind/$templateCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/localization/preview/$kind/$templateCode': typeof LocalizationPreviewKindTemplateCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/localization/preview/$kind/$templateCode': typeof LocalizationPreviewKindTemplateCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/localization/preview/$kind/$templateCode': typeof LocalizationPreviewKindTemplateCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/localization/preview/$kind/$templateCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/localization/preview/$kind/$templateCode'
  id: '__root__' | '/' | '/$' | '/localization/preview/$kind/$templateCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LocalizationPreviewKindTemplateCodeRoute: typeof LocalizationPreviewKindTemplateCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localization/preview/$kind/$templateCode': {
      id: '/localization/preview/$kind/$templateCode'
      path: '/localization/preview/$kind/$templateCode'
      fullPath: '/localization/preview/$kind/$templateCode'
      preLoaderRoute: typeof LocalizationPreviewKindTemplateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LocalizationPreviewKindTemplateCodeRoute:
    LocalizationPreviewKindTemplateCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
