/**
 * TanStack Start router bootstrap.
 *
 * This project's real application is a Vite SPA built on react-router-dom
 * (see src/App.tsx). The Lovable sandbox dev shell, however, invokes the
 * TanStack Start server entry, which requires a `getRouter` export here and
 * the route files under `src/routes/`. We therefore expose the smallest
 * possible TanStack router whose only job is to render `__root` -> `index`,
 * and the index route mounts the existing `<App />` so all real navigation
 * is handled by react-router-dom inside it.
 *
 * Do NOT move app routing into this file — the entire ERP (200+ pages,
 * SubscriptionProtectedRoute, AuthenticatedShell, lazy app modules) lives
 * in src/App.tsx and src/apps/*. Converting that to file-based routes would
 * be a multi-week migration with high regression risk.
 */
import { QueryClient } from "@tanstack/react-query";
// `createRouter` is typed to refuse projects without strictNullChecks; this
// repo intentionally keeps strictNullChecks=false (enabling it cascades into
// hundreds of pre-existing errors elsewhere). Cast through `any` to bypass
// the compile-time guard — runtime behavior is identical.
import { createRouter as createRouterRaw, useRouter } from "@tanstack/react-router";
const createRouter = createRouterRaw as unknown as (opts: any) => any;
// routeTree.gen.ts is generated by @tanstack/router-plugin on first dev run.
// @ts-ignore -- generated file, may not exist before the plugin runs once
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  // Fresh QueryClient per request — never a module-level singleton, which
  // would leak cached auth/tenant data between SSR requests.
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false,
        retry: 1,
        staleTime: 5 * 60 * 1000,
      },
    },
  });

  const router = createRouter({
    routeTree,
    context: { queryClient },
    defaultPreload: "intent",
    scrollRestoration: true,
    defaultErrorComponent: DefaultErrorComponent,
    defaultNotFoundComponent: () => (
      <div style={{ padding: 24, fontFamily: "system-ui" }}>
        <h1>404 — Page Not Found</h1>
      </div>
    ),
  });

  return router;
}

function DefaultErrorComponent({
  error,
  reset,
}: {
  error: Error;
  reset: () => void;
}) {
  const router = useRouter();
  return (
    <div style={{ padding: 24, fontFamily: "system-ui" }}>
      <h2>Something went wrong</h2>
      <pre style={{ whiteSpace: "pre-wrap" }}>{error.message}</pre>
      <button
        onClick={() => {
          router.invalidate();
          reset();
        }}
        style={{ marginTop: 12 }}
      >
        Retry
      </button>
    </div>
  );
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}