-- M3.b — drop HR/payroll schema group (no payroll in Smart Grow Empowerment)
DROP TABLE IF EXISTS
  public.payslip_events, public.payslip_inputs, public.payslip_lines, public.payslips,
  public.payroll_run_loan_skip_overrides, public.payroll_run_issues, public.payroll_run_jobs,
  public.payroll_run_groups, public.payroll_run_type_policies, public.payroll_rule_traces,
  public.payroll_payment_batch_items, public.payroll_payment_batches,
  public.payroll_remittance_payment_allocations, public.payroll_remittance_payments, public.payroll_remittances,
  public.payroll_liability_sources, public.payroll_liabilities,
  public.payroll_bank_export_files, public.payroll_bank_files, public.payroll_batch_readiness_snapshots,
  public.payroll_certificate_template_extensions, public.payroll_certificate_template_overrides,
  public.payroll_correction_adjustments, public.payroll_employee_ytd, public.payroll_filing_calendar_projection,
  public.payroll_input_types, public.payroll_loan_recovery_policy, public.payroll_number_sequences,
  public.payroll_pending_inputs, public.payroll_period_audit, public.payroll_period_close_waivers, public.payroll_periods,
  public.payroll_readiness_findings, public.payroll_readiness_rule_overrides, public.payroll_readiness_rules, public.payroll_readiness_runs,
  public.payroll_reclassification_audit, public.payroll_report_definitions, public.payroll_report_runs,
  public.payroll_return_diagnostics, public.payroll_return_filing_events, public.payroll_return_runs, public.payroll_return_template_overrides,
  public.payroll_rule_types, public.payroll_salary_rules, public.payroll_settings, public.payroll_statutory_rules,
  public.payroll_tax_certificate_events, public.payroll_tax_certificate_submissions, public.payroll_tax_certificates,
  public.payroll_work_entries, public.payroll_work_entry_types, public.payroll_account_role_policy, public.payroll_runs,
  public.pay_schedules,
  public.salary_components, public.salary_structure_lifecycle_events, public.salary_structure_rule_sets, public.salary_structures,
  public.contract_amendments, public.contract_compensation_components, public.employee_contracts, public.employments,
  public.employee_compensation_history, public.employee_position_history, public.employee_lifecycle_events,
  public.employee_profile_change_requests, public.employee_custom_fields, public.employee_field_configs,
  public.employee_statutory_identifiers, public.employee_credentials, public.employee_device_identifiers,
  public.employee_exit_clearance_items, public.employee_exit_clearance,
  public.employee_onboarding_items, public.employee_onboarding, public.onboarding_template_items, public.onboarding_templates,
  public.employee_benefits, public.benefit_plans, public.benefit_enrollment_windows,
  public.employee_custom_deduction_events, public.employee_custom_deductions, public.custom_deduction_types,
  public.advance_repayment_schedule, public.employee_advances, public.employee_loans,
  public.garnishment_audit_log, public.garnishment_carry_forward, public.garnishment_kind_defaults, public.garnishment_lifecycle_events,
  public.legal_order_authorities, public.legal_order_documents, public.legal_order_event_dispatch_log, public.legal_order_kind_overrides,
  public.legal_order_remittance_batch_lines, public.legal_order_remittance_batches, public.legal_order_remittance_lines,
  public.legal_order_statutory_report_definitions, public.legal_order_subscriber_dispatch_log, public.legal_orders_records,
  public.statutory_authorities, public.statutory_reporting_bindings, public.statutory_scheme_components, public.statutory_schemes,
  public.country_statutory_catalog,
  public.leave_allocations, public.leave_requests, public.leave_types, public.overtime_requests,
  public.attendance_breaks, public.attendance_device_trust, public.attendance_devices, public.attendance_events,
  public.attendance_ingest_log, public.attendance_saved_views, public.attendance,
  public.shift_assignments, public.shift_swap_requests, public.shifts, public.work_schedule_days, public.work_schedules
CASCADE;