// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwxqunklduknceoryrha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3eHF1bmtsZHVrbmNlb3J5cmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4Nzc4MzcsImV4cCI6MjEwMzQ1MzgzN30.6zYTXR-rdy8XJ2wPgxgYHTIQj-BpvDrf03H98kTYfVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});