/**
 * Contractual repayment schedule and loan event history (C6).
 *
 * Read-only: the schedule is the contract, not the payment ledger, and it is
 * produced entirely by the server-side schedule engine.
 */
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { LoadingState, EmptyState } from "@/design-system";
import { useMfLoanSchedule, type MfLoan } from "@/hooks/useMfLoans";
import { DisbursementPhotoPanel } from "./DisbursementPhotoPanel";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  loan: MfLoan | null;
  /** Registration portrait of the borrowing client, for payout comparison. */
  clientPhotoPath?: string | null;
}

const money = (v: number) =>
  Number(v ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function LoanScheduleDialog({ open, onOpenChange, loan, clientPhotoPath }: Props) {
  const { schedule, events, penalties, isLoading } = useMfLoanSchedule(
    open ? loan?.id : undefined,
  );

  const penaltyByInstallment = new Map(penalties.map((p) => [p.installment_no, p]));
  const penaltyOutstanding = penalties.reduce(
    (acc, p) => acc + Number(p.penalty_outstanding ?? 0),
    0,
  );
  const penaltyCharged = penalties.reduce((acc, p) => acc + Number(p.penalty_charged ?? 0), 0);

  /**
   * Upfront-interest loans carry zero stored interest, so the display view
   * re-splits the installment. Showing the earned column only when the split
   * differs keeps ordinary loans looking exactly as before.
   */
  const hasDeferredInterest = schedule.some(
    (r) => Number(r.interest_component ?? 0) !== Number(r.interest_due ?? 0),
  );

  const totals = schedule.reduce(
    (acc, r) => ({
      principal: acc.principal + Number(r.principal_component ?? r.principal_due),
      interest: acc.interest + Number(r.interest_component ?? r.interest_due),
      fees: acc.fees + Number(r.fees_due),
      total: acc.total + Number(r.total_due),
      recognised: acc.recognised + Number(r.interest_recognised ?? 0),
    }),
    { principal: 0, interest: 0, fees: 0, total: 0, recognised: 0 },
  );


  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>Repayment schedule — {loan?.loan_number}</DialogTitle>
          <DialogDescription>
            Contractual installments generated by the schedule engine. This is not the
            payment ledger.
          </DialogDescription>
        </DialogHeader>

        <DisbursementPhotoPanel
          loanId={loan?.id ?? null}
          clientPhotoPath={clientPhotoPath}
          enabled={open && !!loan?.disbursed_at}
        />

        {isLoading ? (
          <LoadingState />
        ) : schedule.length === 0 ? (
          <EmptyState title="No schedule" description="This loan has no schedule rows." />
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>#</TableHead>
                <TableHead>Due</TableHead>
                <TableHead className="text-right">Opening</TableHead>
                <TableHead className="text-right">Principal</TableHead>
                <TableHead className="text-right">Interest</TableHead>
                {hasDeferredInterest && (
                  <TableHead className="text-right">Interest earned</TableHead>
                )}
                <TableHead className="text-right">Fees</TableHead>
                <TableHead className="text-right">Penalty due</TableHead>
                <TableHead className="text-right">Total</TableHead>
                <TableHead className="text-right">Closing</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {schedule.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="tabular-nums">{r.installment_no}</TableCell>
                  <TableCell className="whitespace-nowrap">{r.due_date}</TableCell>
                  <TableCell className="text-right tabular-nums">
                    {money(r.opening_balance)}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {money(r.principal_component ?? r.principal_due)}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {money(r.interest_component ?? r.interest_due)}
                  </TableCell>
                  {hasDeferredInterest && (
                    <TableCell className="text-right tabular-nums">
                      {money(r.interest_recognised ?? 0)}
                    </TableCell>
                  )}
                  <TableCell className="text-right tabular-nums">{money(r.fees_due)}</TableCell>
                  <TableCell className="text-right tabular-nums">
                    {money(penaltyByInstallment.get(r.installment_no)?.penalty_outstanding ?? 0)}
                  </TableCell>
                  <TableCell className="text-right font-medium tabular-nums">
                    {money(r.total_due)}
                  </TableCell>
                  <TableCell className="text-right tabular-nums">
                    {money(r.closing_balance)}
                  </TableCell>
                </TableRow>
              ))}
              <TableRow>
                <TableCell colSpan={3} className="font-medium">
                  Totals
                </TableCell>
                <TableCell className="text-right font-medium tabular-nums">
                  {money(totals.principal)}
                </TableCell>
                <TableCell className="text-right font-medium tabular-nums">
                  {money(totals.interest)}
                </TableCell>
                {hasDeferredInterest && (
                  <TableCell className="text-right font-medium tabular-nums">
                    {money(totals.recognised)}
                  </TableCell>
                )}
                <TableCell className="text-right font-medium tabular-nums">
                  {money(totals.fees)}
                </TableCell>
                <TableCell className="text-right font-medium tabular-nums">
                  {money(penaltyOutstanding)}
                </TableCell>
                <TableCell className="text-right font-medium tabular-nums">
                  {money(totals.total)}
                </TableCell>
                <TableCell />
              </TableRow>
            </TableBody>

          </Table>
        )}

        {penalties.length > 0 && (
          <div className="space-y-1 border-t pt-3">
            <p className="text-sm font-medium">
              Penalty charges — {money(penaltyCharged)} charged, {money(penaltyOutstanding)}{" "}
              outstanding
            </p>
            <ul className="space-y-1 text-xs text-muted-foreground">
              {penalties.map((p) => (
                <li key={p.installment_no}>
                  Installment {p.installment_no} · charged {money(p.penalty_charged)} · paid{" "}
                  {money(p.penalty_paid)} · outstanding {money(p.penalty_outstanding)}
                </li>
              ))}
            </ul>
          </div>
        )}

        {events.length > 0 && (
          <div className="space-y-1 border-t pt-3">
            <p className="text-sm font-medium">Loan events</p>
            <ul className="space-y-1 text-xs text-muted-foreground">
              {events.map((e) => (
                <li key={e.id}>
                  <span className="font-mono">{new Date(e.event_at).toLocaleString()}</span>{" "}
                  — {e.event_type.replace(/_/g, " ")}
                  {e.amount != null ? ` · ${money(Number(e.amount))}` : ""}
                </li>
              ))}
            </ul>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
